lsst/rubin_scheduler

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/site_models/almanac.py
Let the model observatory keep running all the way to sunrise/sunset before it forces a jump to the next night.
> modelobservatory can run all the way to sunrise and set

- .github/workflows/test_and_build.yaml
- pyproject.toml
- rubin_scheduler/scheduler/utils/footprints.py
- rubin_scheduler/utils/coordinate_transformations.py
- rubin_scheduler/utils/htm_module.py
- rubin_scheduler/utils/riseset.py
- rubin_scheduler/utils/tree_utils.py
- test-requirements.txt
- tests/utils/test_modules/dummy_module.py
See discussion [here](https://lsstc.slack.com/archives/G6MP1HTDW/p1706547380936619).
> tickets/PREOPS-4846:  update rubin_scheduler for pytest 8 and black 24

- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/utils/tsp.py
- rubin_scheduler/scheduler/utils/utils.py
Tracking down yet another sneaky spot where things can become not cross-platform repeatable.
> IntRounded into TSP code

- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/utils/tsp.py
Refactor of code so there's now a handy utility to run the traveling salesman optimizer on a list of RA,Dec points.
> move path optimization out of survey object

- rubin_scheduler/scheduler/utils/utils.py
- tests/scheduler/test_utils.py
Let SchemaConverter append to an already existing sqlite file, added unit test.
> let SchemaConverter append to an already existing sqlite file

- rubin_scheduler/scheduler/utils/sky_area.py
Make sure opened files get closed after reading.
> load with context manager

- rubin_scheduler/utils/season_utils.py
Season zero-point needs to be defined by a time and RA to be repeatable for multiple calls. 
Also moved some example commented code into a real function.
> add mjd_start to calc_season

- rubin_scheduler/scheduler/surveys/surveys.py
Have to wrap things up in case reward is all NaNs.
> another fix for minimum area survey

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
Use the proper starting time to decide if the observatory should skip to the next night.
> fix skip night ahead bug

- docs/installation.rst
Compactify the developer install instructions a bit.
> install instruction clarification

- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/schedulers/filter_scheduler.py
- rubin_scheduler/scheduler/sim_runner.py
Make sure `sim_runner` always sets the mounted filters properly and repeatably.
> filter scheduler always use moon phase at sunset

- rubin_scheduler/skybrightness_pre/sky_model_pre.py
- tests/skybrightness_pre/test_skypre.py
Update `SkybrightnessPre` so it returns a "bright" sky map rather than the nearest twilight map if a time during the day is requested.
> OPSIM-1151: return a bright sky map if time requested when sun is up

- pyproject.toml
- rubin_scheduler/scheduler/sim_runner.py
- rubin_scheduler/sim_archive/__init__.py
- rubin_scheduler/sim_archive/prenight.py
- tests/sim_archive/test_prenight.py
I am also using this code to experiment with type hints and configuring my IDE to use them.
VScode's type inlays (which attempt to automatically figure out types for you by analyzing the code) and the monkeytype tool (which try to do the same by looking at the code as it is run, eg by tests) are both helpful, but neither actually "do the job for you."
> tickets/PREOPS-5156: Create driver for sets of pre-night opsim simulations

- rubin_scheduler/utils/ddf_locations.py
Added missing return. Fixed mixed camel and snake case name.
> add switch to use old ddf locs

- rubin_scheduler/scheduler/model_observatory/kinem_model.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/surveys/too_surveys.py
- tests/scheduler/test_utils.py
Update default camera readout time to 2.4 seconds
> increase read time to 2.4s

- rubin_scheduler/scheduler/features/features.py
Some patches to make get add_observation_array working. I'll call it a future ticket to make a unit test that goes through and does a rough job testing `add_observation` and `add_observation_array` and checks for consistency.
> Fix bug in "NObsSurvey" feature to add_observation/add_observation_array

- rubin_scheduler/scheduler/surveys/ddf_presched.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/utils/utils.py
update "target" to "target_name" on schema for `observation` object to match downstream schema.
> convert observation schema from target to target_name

- rubin_scheduler/scheduler/example/example_scheduler.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/ddf_presched.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/long_gap_survey.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/surveys/too_surveys.py
- rubin_scheduler/scheduler/utils/utils.py
- tests/scheduler/test_baseline.py
- tests/scheduler/test_surveys.py
- tests/scheduler/test_utils.py
Add "science_program", "observation_reason" and "json_block" to observation
Modify FieldSurvey so it can accept only particular scheduler_note and depends directly on ScriptedSurvey.
> OPSIM-1174: modify FieldSurvey, add new fields to observation

- rubin_scheduler/scheduler/model_observatory/kinem_model.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/site_models/unscheduled_downtime_data.py
- tests/scheduler/test_baseline.py
- tests/scheduler/test_utils.py
- tests/site_models/test_unscheduleddowntimedata.py
Update default unscheduled downtime to have more year 1 downtime. Update default telescope jerk values.
> OPSIM-1178: update defaults to add more downtime in year and add jerk 

- requirements.txt
Scipy and Healpy clashes are now fixed in healpy.
> Unpin scipy

- rubin_scheduler/scheduler/surveys/field_survey.py
Downstream failures in ts_fbs_utils, so replacing the kwarg for now.
> OPSIM-1181: backwards compatibility for field survey kwargs

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/surveys.py
- tests/scheduler/test_baseline.py
add `target_name`, `science_program`, and `observation_reason` as `Survey` kwargs. Any of them set on init will then go into a `Detailer` object that updates all observations coming out of the `Survey`.
> info into detailer

- docs/archive.rst
- docs/fbs-api-example-scheduler.rst
- docs/fbs-output-schema.rst
- docs/user-guide.rst
Update schema so it works again, and matches current schema. 
Add archive to the pages that display.
Add other examples in rubin_scheduler.scheduler.example into the API docs.
> Bring documentation up to date

- rubin_scheduler/utils/healpy_utils.py
- tests/utils/test_healutils.py
Mask growth only worked properly for small angles, now works for any mask padding size. Extended unit tests to include angles on many scales.
> fix healpy mask growth to work beyond small angle approx

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- tests/scheduler/test_surveys.py
Add a field survey that uses alt,az rather then ra,dec.
> SP-1722: add FieldAltAzSurvey

- rubin_scheduler/scheduler/detailers/dither_detailer.py
Followup to bad merge decision on previous SP-1737 ticket.
> SP-1737: Fix tab formatting error

- rubin_scheduler/scheduler/detailers/dither_detailer.py
This PR adds a detailer to synthesize a 2x2 grid of ComCam pointings
> SP-1745: Add ComCamGridDitherDetailer to scheduler config

- rubin_scheduler/scheduler/detailers/dither_detailer.py
Patch ComCamGridDitherDetailer
> SP-1751: Patch ComCamGridDitherDetailer

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
Full position of the sun was not being passed in the `Conditions` object
> missing sun azimuth

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/detailers/dither_detailer.py
- rubin_scheduler/scheduler/detailers/vary_exptime.py
- rubin_scheduler/scheduler/utils/utils.py
- tests/scheduler/test_utils.py
Add some methods/functions so it's easier to avoid loops in `Detailer` objects.
> add tolist method and obsarray_concat function

- rubin_scheduler/scheduler/detailers/detailer.py
Making sure pairs are labeled and executed in the proper order.
> Correct pairs to minimize filter changes

- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/roman_surveys.py
- rubin_scheduler/sim_archive/sim_archive.py
- tests/sim_archive/test_sim_archive.py
Minor updates to get rid of deprecation warnings.
> fix FutureWarning and DeprecationWarning

- rubin_scheduler/scheduler/detailers/dither_detailer.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/utils/utils.py
- rubin_scheduler/sim_archive/sim_archive.py
- rubin_scheduler/utils/riseset.py
- tests/scheduler/test_detailers.py
Detailer to support adding arbitrary dither positions to a selected pointing.
> arbitrary dither pattern detailer

- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/surveys.py
Consolidate some repeated code into new method `calc_reward_basic`. Make sure the tests for if a survey has enough area are only being handled in one place with one relevant kwarg.
> refactor to eliminate duplicate kwargs min_area and area_required

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/example/example_scheduler.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/utils/observation_array.py
- rubin_scheduler/site_models/seeing_model.py
- rubin_scheduler/skybrightness_pre/sky_model_pre.py
- tests/scheduler/test_basisfuncs.py
The previous pr for backwards compatibility missed filter/band swaps in the Models, so this is corrected here.
> SP-1865: Add filter backwards-compatibility to models

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/utils/observation_array.py
- rubin_scheduler/scheduler/utils/utils.py
- rubin_scheduler/site_models/seeing_model.py
- tests/scheduler/test_detailers.py
Missed that ts_scheduler was using defaults for SeeingModel setup, so didn't trigger the setting of self.filter_list.
> SP-1865: Additional changes for use with ts_scheduler v2.3

- rubin_scheduler/scheduler/detailers/dither_detailer.py
- tests/scheduler/test_detailers.py
Update euclid detailer to use latest scheduler_note convention.
> euclid dither fix

- rubin_scheduler/scheduler/surveys/surveys.py
Set kwarg so numpy.argsort is cross-version and cross-platform stable.
> add mergesort kwarg to np.argsort

- rubin_scheduler/skybrightness_pre/sky_model_pre.py
Make sure extrapolation works in non-all sky cases.
> fix partial sky extrapolation

- rubin_scheduler/scheduler/basis_functions/mask_basis_funcs.py
- tests/scheduler/test_basisfuncs.py
New basis function that can generate a mask in alt and az that only turns on at certain points of the night. 
Very open to suggestions for a shorter class name.
> add AltAzShadowTimeLimitedBasisFunction

- rubin_scheduler/scheduler/schedulers/core_scheduler.py
adding requested setters for `CoreScheduler` attributes.
> add setters to CoreScheduler

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/rolling_funcs.py
Rouge old `set_default_nside` that was still floating around
> kwarg default fixes

- rubin_scheduler/scheduler/utils/utils.py
Make `IntRounded` smarter so it only converts values to ints if there's a potential that a comparison will be near the machine-precision limit.
> Turn down IntRounded warning messages, convert to int only if needed

- rubin_scheduler/scheduler/surveys/roman_surveys.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Make sure ToO and Roman surveys have lunar and wind avoidance.
> add moon wind avoidance to ToOs and Roman

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/example/example_scheduler.py
- tests/scheduler/test_detailers.py
Detailer to combine `LabelRegionDetailer` and `LabelDDFDetailer` into one.
> label detailers

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
Previously, the scheduler set `rotSkyPos_desired` and `rotTelPos_backup` to ensure each observation could have a valid rotation angle set. Now, the scheduler sets only `rotSkyPos`, and if that value is invalid, `ModelObservatory` tries rotating the requested value by -90, 90, -180, and 180 degrees to find a valid rotation. This should more closely emulate what happens at the telescope.
> resolve rotSkyPos if out of range in ModelObservatory

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Minor changes to lensed BNS strategy, as a result of testing. See [slack](https://rubin-obs.slack.com/archives/C08Q47VJZJ7/p1748105087008959) for report on testing
> Adding changes to lensed BNS strategy from testing

- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/detailers/dither_detailer.py
- tests/scheduler/test_detailers.py
These are new detailers that are needed as part of an upcoming DDF change. 
To use them for the SV survey, they need  to be added to rubin_scheduler now.
> SP-2350: Add new BandSort and SplitDither detailers

- rubin_scheduler/scheduler/surveys/roman_surveys.py
- rubin_scheduler/utils/ddf_locations.py
- tests/utils/test_locations.py
Function to hold ""special locations" like Roman bulge field postion.
> SP-2420: Add utility function for special targets (Roman field)

- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Add `update_conditions` method to `Survey` objects so ToO surveys can generate list of desired observations before reward functions are called.
> add update_conditions method to Survey objects.

- rubin_scheduler/utils/__init__.py
- rubin_scheduler/utils/parallel_utils.py
- tests/utils/test_para_utils.py
Handy utility for sharing numpy arrays when using multiprocessing.
> add shared numpy array tool

- rubin_scheduler/scheduler/detailers/dither_detailer.py
- tests/scheduler/test_detailers.py
Update dither detailers so they do not have to pre-generate every potential dither position.
> generate offsets on the fly to save mem

- rubin_scheduler/scheduler/detailers/dither_detailer.py
- tests/scheduler/test_detailers.py
Make sure dither detailer can handle negative nights. Get rid of DeprecationWarning in the Euclid detailer.
> deal with negative nights and fix dep warning
