- README.md
- pyproject.toml
- rubin_scheduler/data/scheduler_download_data.py
refactor the download data code so it will be easier to import and call from `rubin_sim`.
> refactor download data

- rubin_scheduler/utils/coordinate_transformations.py
- tests/utils/test_coordinatetransformations.py
Astropy is painfully slow for computing LMST. Substituting in a fast calculation, unit test will catch if it gets more than 2 seconds out of sync with astropy
> use fast approx for LMST

- rubin_scheduler/scheduler/model_observatory/kinem_model.py
Nasty little typo that resulted in some rare long slew times because the kinematic model thought it had to make a large rotation.
> swap starting_pa for pa typo

- docs/fbs-api-basis-functions.rst
- docs/fbs-api-detailers.rst
- docs/fbs-api-example-scheduler.rst
- docs/fbs-api-features.rst
- docs/fbs-api-model-observatory.rst
- docs/fbs-api-schedulers.rst
- docs/fbs-api-sim-runner.rst
- docs/fbs-api-surveys.rst
- docs/fbs-api-utils.rst
- docs/fbs-api.rst
Make it easier to find specific classes relating to the scheduler within the FBS API documentation.
> Add drop-down for FBS scheduler pieces

- .github/workflows/build_docs.yaml
- .github/workflows/test_and_build.yaml
- pyproject.toml
- requirements.txt
- rubin_scheduler/scheduler/example/example_scheduler.py
- rubin_scheduler/sim_archive/__init__.py
- rubin_scheduler/sim_archive/sim_archive.py
- rubin_scheduler/site_models/almanac.py
- tests/sim_archive/test_sim_archive.py
- tests/site_models/test_almanac.py
This pull needs to be coordinated with the corresponding PR on schedview.
> tickets/PREOPS-4646: Support addition of opsim data to an archive for use by schedview-prenight

- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- tests/scheduler/test_utils.py
Update scripted surveys to have logic that will prevent long sequences from executing right before twilight. Mainly for DDFs.
> let scripted observations check for twilight starting

- rubin_scheduler/skybrightness_pre/sky_model_pre.py
- tests/skybrightness_pre/test_skypre.py
This enables loading sky brightness files directly from the http directory, or (if/when there eventually is one) an s3 bucket.
This is intended for use in the containers running dashboards at the USDF.
> tickets/PREOPS-4736: Support loading of sky brightess with lsst.resources in rubin_scheduler

- rubin_scheduler/scheduler/model_observatory/__init__.py
- rubin_scheduler/scheduler/model_observatory/jerk.py
- rubin_scheduler/scheduler/model_observatory/kinem_model.py
- tests/scheduler/test_modelobs.py
Update the kinematic model of the telescope to include jerk. All jerks and accelerations assumed to be symmetric (e.g., maximum deceleration equals negative maximum acceleration). Removed previously unused deceleration kwargs.
> Tickets/opsim 1114 Add jerk to the telescope kinematic model

- rubin_scheduler/scheduler/utils/utils.py
Expand documentation on the rotTelPos and rotSkyPos options within the observation object.
> rotator documentation

- rubin_scheduler/sim_archive/__init__.py
- rubin_scheduler/sim_archive/sim_archive.py
Because we want to be able to pip install rubin_scheduler, and conda isn't a pip package.
> tickets/PREOPS-4836: make conda package optional in rubin_scheduler

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- tests/scheduler/test_modelobs.py
Rather than a global "ideal" kwarg, be able to individually set seeing, clouds, and downtime to "ideal". Inspired by folks who wanted to simulate without clouds or downtime, but still wanted realistic seeing distribution.
> easier to run model observatory with ideal conditions

- rubin_scheduler/scheduler/utils/tsp.py
Snippet of code that was supposed to be helping with cross-platform repeatability, but there was a sneaky square root converting ints to floats, so removed some unneeded float to ints.
> move IntRounded

- rubin_scheduler/scheduler/surveys/ddf_presched.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/utils/utils.py
Include a moon distance limit for scheduled observations. Prevents observations that are delayed a few days from having the moon sneak up on them.
> Include a moon distance limit for scheduled observations.

- rubin_scheduler/scheduler/utils/footprints.py
- tests/scheduler/test_utils.py
This PR adds new uniform/optimized rolling functionality to the scheduler. It allows for special times during rolling surveys where the survey will come back to uniform. 
See PRs https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/4 and https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/3 for detailed tests.
This PR has the scheme in https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/4.
> ENH add uniform/optimized rolling and tests for it

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/feasibility_funcs.py
- rubin_scheduler/scheduler/basis_functions/rolling_funcs.py
- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/features/features.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/surveys/ddf_presched.py
- rubin_scheduler/scheduler/utils/footprints.py
- rubin_scheduler/scheduler/utils/sky_area.py
- rubin_scheduler/scheduler/utils/utils.py
- rubin_scheduler/utils/season_utils.py
- tests/scheduler/test_features.py
While almost all of the time calc_season would be called with only a single RA, if it's confusing, we can make it multi-RA like this.
More importantly though, it does update the "zero point" for the seasons, to introduce the discontinuity in season count that exists in the scheduler code ..  This PR makes calc_season start counting at 1, and counting 'season' as starting when the RA value matches the RA of the Sun.  
I think this still offsets the zero point for the seasons by about 90 degrees from what the scheduler counts as the "start" of the season though.  I'm not sure if this is going to remain confusing or not.
```
import numpy as np
import matplotlib.pyplot as plt
from rubin_scheduler.utils import survey_start_mjd, calc_season
ra = np.arange(0, 360, 1)
mjds = …
```
> OPSIM-1136: Update zero point for calc_season and make it multi-RA capable

- rubin_scheduler/scheduler/surveys/scripted_surveys.py
A fix so scripted surveys do not propose observations where the needed filter is not loaded.
> OPSIM-1154 scripted survey check filter loaded

- rubin_scheduler/scheduler/utils/utils.py
The OR4 V4 opsim DB has a `psudoParaAngle` column of type `object` and value `None`, and `opsim2obs` throws an unhandled exception when it tries to convert this to degrees. Instead, catch the exception and set it to all `nan`.
>  tickets/PREOPS-5256: make rubin_scheduler.scheduler.utils.SchemaConverter.opsim2obs robust to columns of unexpected type

- batch/run_prenight_sims.sh
- pyproject.toml
- requirements.txt
- rubin_scheduler/sim_archive/__init__.py
- rubin_scheduler/sim_archive/make_snapshot.py
- rubin_scheduler/sim_archive/prenight.py
- rubin_scheduler/sim_archive/sim_archive.py
- tests/sim_archive/test_make_snapshot.py
- tests/sim_archive/test_prenight.py
This cron job needs to be update manually for new configurations. Automatic coordination of versions with the observatory version is PREOPS-5280.
> tickets/PREOPS-5190: Automatically run one-night auxtel sims daily to support the prenight briefing

- rubin_scheduler/utils/ddf_locations.py
I seem to pull the ddf locations and turn them into SkyCoords fairly often, and given that the white paper specifies them in SkyCoord style, I thought this might be easier.
> Update DDF locations to 2018 white paper

- rubin_scheduler/scheduler/utils/utils.py
- rubin_scheduler/utils/consdb.py
- rubin_scheduler/utils/rotskypos.py
- tests/utils/test_consdb.py
There is (or will be shortly) a corresponding pull request in schedview.
> tickets/PREOPS-5245: Add support for reading visits from ConsDB 

- rubin_scheduler/scheduler/surveys/surveys.py
- tests/scheduler/test_utils.py
Fix issue where flush times were being set too short (because they were being computed in two places).
> PREOPS-5366: remove old minimum pair time kwarg since blob no longer adjust pair time

- rubin_scheduler/scheduler/basis_functions/feasibility_funcs.py
- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/surveys/__init__.py
- rubin_scheduler/scheduler/surveys/roman_surveys.py
- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
- rubin_scheduler/scheduler/utils/footprints.py
- rubin_scheduler/scheduler/utils/sky_area.py
- tests/scheduler/test_detailers.py
- tests/scheduler/test_utils.py
Updates generated in v3.5 sims. 
* updated default footprint
* Roman overlap survey
* ToO surveys
> OPSIM-1180: Updates to bring rubin_scheduler in line with v3.5 simulations

- rubin_scheduler/scheduler/surveys/surveys.py
Eliminate an unnecessary ra,dec to alt,az conversion. Was probably originally stuck in there at some point because of a degrees,radians issue downstream.
> tickets/OPSIM-1184: use ra/dec to order

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/mask_basis_funcs.py
- rubin_scheduler/scheduler/example/comcam_sv_scheduler_example.py
- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/model_observatory/kinem_model.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/sim_runner.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/utils/site.py
- tests/scheduler/test_basisfuncs.py
- tests/scheduler/test_utils.py
I expect this PR could have downstream effects on what is scheduled .. depending on how the observatory kinematic model is set up. 
For a fully functioning telescope, with >360 degrees of rotator azimuth range, I don't think it would have that much of an effect. However, it's also true that if we're bumping up against the cumulative azimuth range, this might be an incorrect statement. Depends on the configuration of the AltAzShadowMaskBasisFunction itself during use. 
The kinematic model will now return valid slew times over the parts of the sky which are valid, if provided "no filter" or if given rotSkyPos. This again should have no effect on the actual operations of the kinematic model during baseline sim_runner use, but is useful when trying to diagnose issues later or to just …
> OPSIM-1175: update the kinematic model and altazshadowmask basis function

- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- tests/scheduler/test_comcam.py
- tests/scheduler/test_filterschedulers.py
- tests/scheduler/test_simple_examples.py
Remove unused attributes from `Conditions` object.
> remove extras from Conditions object

- tests/utils/test_coordinatetransformations.py
Unit test passes on github, but fails on my laptop. Increasing LMST tolerance from 2 seconds to 3 seems to fix it.
> increase fast coord tolerance by 1 second

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/mask_basis_funcs.py
- rubin_scheduler/scheduler/example/example_scheduler.py
- rubin_scheduler/scheduler/features/features.py
- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/sim_runner.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/dd_surveys.py
- rubin_scheduler/scheduler/surveys/ddf_presched.py
- rubin_scheduler/scheduler/surveys/desc_ddf.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/long_gap_survey.py
- rubin_scheduler/scheduler/surveys/pointings_survey.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
- rubin_scheduler/scheduler/utils/utils.py
- tests/scheduler/test_basisfuncs.py
- tests/scheduler/test_coresched.py
- tests/scheduler/test_detailers.py
- tests/scheduler/test_example.py
- tests/scheduler/test_features.py
- tests/scheduler/test_surveys.py
- tests/scheduler/test_utils.py
Make `ObservationArray` and `ScheduledObservationArray` subclasses of numpy arrays. Also dropping `JSON_Block` from the schema.
Quick test shows there's no performance hit making the change. Previous convienince functions updated to be backwards compatible and throw a warning.
> Tickets/opsim 1157: Change observations to proper numpy subclass

- rubin_scheduler/scheduler/utils/footprints.py
- rubin_scheduler/scheduler/utils/sky_area.py
- tests/scheduler/test_skyarea.py
`make_rolling_footprint` now works with default kwarg values. Had to shuffle a few things around to avoid circular imports. Removed a strange duplicate `_is_in_ra_range` function (strange ruff never noticed that). Added bare-bones unit test for `make_rolling_footprint`.
> OPSIM-1192: make_rolling_footprint work with default values

- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- tests/scheduler/test_modelobs.py
Update `ModelObservatory` so it can handle downtime events that are shorter than 1 day.
> let unscheduled downtimes be less than a day

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/mask_basis_funcs.py
- rubin_scheduler/scheduler/example/simple_examples.py
- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/features/features.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/utils/sky_area.py
- rubin_scheduler/scheduler/utils/utils.py
- tests/scheduler/test_basisfuncs.py
- tests/scheduler/test_features.py
- tests/scheduler/test_simple_examples.py
- tests/scheduler/test_skyarea.py
- tests/scheduler/test_surveys.py
- tests/scheduler/test_utils.py
Defines tel_alt_limits and tel_az_limits as the kinematic / observatory model limits for alt and az.
Defines sky_alt_limits and sky_az_limits as the on-sky (potentially disjoint) limits for alt and az.
Remove empty_observation and scheduler_observation completely.
Remove unused kwargs for FieldSurvey (reward_value and nexp).
> OPSIM-1196: more cleanup for summit use

- rubin_scheduler/scheduler/example/example_scheduler.py
Lots of docstring formatting in example_scheduler.py
> docstring updating

- rubin_scheduler/utils/consdb.py
Queries to the consdb now return a 2d array rather than a 1d array. Let ConsDBVisits (required by schedview_notebooks notebooks that query the consdb) handle this.
> tickets/SP-1675: accommodate new shape of seq_num in the consdb

- rubin_scheduler/utils/consdb.py
Previously, the consdb tools in rubin_scheduler could only query visits for one night at a time. To support DDF cadence plots (needed to merge the different version of the night summary for SP-1667), all nights to be included in the DDF plot should be queryable at once.
> tickets/SP-1667: support reading multiple nights

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Update ToO surveys so they populate the `target_name` field.
> add target_name to observations competed by ToO surveys

- rubin_scheduler/scheduler/basis_functions/mask_basis_funcs.py
Adding deprecation warning to `SolarElongMaskBasisFunction` since it seems to be redundant with `SolarElongationMaskBasisFunction`.
> Dep warning added to SolarElongMaskBasisFunction

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Adding some additional kwargs for ToO setup to ensure we don't run into the regime where long exposures would saturate on the sky background.
> Make sure ToO surveys won't saturate if nsnaps is set to 1

- rubin_scheduler/scheduler/detailers/dither_detailer.py
CameraRotSmallDitherDetailer was losing the large offsets to rotation angle between filter changes after the first visit in each filter in a sequence, and going back to only keeping the small per-visit offset.
> Fix bug in CameraRotSmallDitherDetailer

- docs/fbs-output-schema.rst
- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/utils/__init__.py
- rubin_scheduler/scheduler/utils/observation_array.py
- rubin_scheduler/scheduler/utils/utils.py
Added `target_id` to scheme which gets filled in by `CoreScheduler`. Removed `note` and `block_id` from schema.
> Tickets/sp 1786: Adding target_id

- rubin_scheduler/scheduler/utils/footprints.py
Make it so if `filters` kwarg to `Footprint` can be an iterable string or list and it will get auto converted to a dict for internal use.
> swap Footprint object to take list of filters rather than dict

- rubin_scheduler/scheduler/basis_functions/basis_functions.py
- rubin_scheduler/scheduler/basis_functions/feasibility_funcs.py
- rubin_scheduler/scheduler/basis_functions/rolling_funcs.py
- rubin_scheduler/scheduler/detailers/detailer.py
- rubin_scheduler/scheduler/detailers/short_survey.py
- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/features/features.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/field_survey.py
- rubin_scheduler/scheduler/surveys/scripted_surveys.py
- rubin_scheduler/scheduler/surveys/surveys.py
- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
- rubin_scheduler/scheduler/surveys/too_surveys.py
- rubin_scheduler/scheduler/utils/footprints.py
- rubin_scheduler/scheduler/utils/observation_array.py
- tests/scheduler/test_basisfuncs.py
This PR has the goal to make the move from "filter" to "band" backwards compatible. 
This lets us tag at 3.5.0, making the band update a "feature" rather than breaking change, and lets @tribeiro deploy this at the summit without having to make over ts_scheduler. 
I've tested this with the current develop of ts_fbs_utils and the unit tests there run. I've also tested it with sim_runner and our baseline survey configuration. 
I am unsure of how to test this in a full run with ts_scheduler to ensure there are no breakages (this is technically true for any update we make). 
It would be good if both @tribeiro and @yoachim could take a look. 
The main place I am concerned about is in the Conditions object and in add_observation.
* in the Conditions: ts_scheduler currently reaches into the …
> SP-1841: Backwards compatible updates for Band/Filter

- rubin_scheduler/scheduler/example/example_scheduler.py
- rubin_scheduler/scheduler/surveys/ddf_presched.py
Refactor DDF schedulign code a bit in an attempt to make it a little easier for others to come in and use it. 
* Made `optimize_ddf_times` the only spot where scheduling logic parameters are set
* Removed magic numbers and COSMOS specific bits from `ddf_slopes` (this does make it return results that are not exact matches to previous versions)
* Converted `min_season_length` kwarg to be in days rather than a unitless fraction.
> refactor ddf_presched to make config easier. eliminate magic numbers

- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/scheduler/surveys/base_survey.py
- rubin_scheduler/scheduler/surveys/too_surveys.py
Subclasses of the `Survey` object do not always run the base `__init__` method, so can fail to map band to filter.
> move band to filter mapping to CoreScheduler

- rubin_scheduler/utils/consdb.py
- tests/utils/test_consdb.py
I have included a URL for the endpoint to be used at the summit, but at this point its just a guess based on the EFD URLs.
> tickets/SP-2013: switch to using the REST API for consdb in rubin_scheduler so it can work from anywhere with a token

- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- tests/scheduler/test_coresched.py
Logs from pre-night sims are being flooded with these useless warnings. Get rid of them.
> tickets/SP-2046: Quiet the benign "RuntimeWarning: All-NaN axis encountered" warnings when rubin_scheduler is run with reward recording turned on

- pyproject.toml
- requirements.txt
Remove gitpython and conda from requirements.txt and pyproject.toml after moving the module that used these into rubin-sim.
> SP-2902: Remove gitpython and conda following sim_archive move

- rubin_scheduler/scheduler/detailers/detailer.py
- tests/scheduler/test_detailers.py
Detailer so one can copy values from one column to another, e.g., `scheduler_note` to `target_id`.
> copy column detailer

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
- rubin_scheduler/scheduler/utils/utils.py
Make sure a footprint set by a ToO event object can be any nside and `Survey` object will change resolution if needed.
> ToO maps can be any nside

- rubin_scheduler/utils/site.py
- tests/utils/test_site.py
Update the LSST site position. Add the position of auxtel. Test on 1-year sims shows this had no impact on scheduler decisions. There is potential for things to change if the per-calculated DDF positions are updated.
> update LSST site postion, add auxtel site

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Very minor change, but a duplicate call of detailer definition on the ToO scripted survey is removed here.
> Update too_scripted_surveys.py to remove duplicate detailers call

- rubin_scheduler/data/scheduler_download_data.py
- rubin_scheduler/scheduler/surveys/generate_ddf_grid.py
Update so we have 15 min and 5 min DDF pre-computed resolution files.
> SP-2378: Add 5-min sampled DDF grid

- rubin_scheduler/utils/consdb.py
- tests/utils/test_consdb.py
This a a short-term fix to support querying just SV visits until we work through SP-2442.
> tickets/SP-2444: stop-gap to support getting only sv visits

- rubin_scheduler/scheduler/surveys/too_scripted_surveys.py
Original intent of this PR was to re-evaluate all flush times. It turns out we only need to adjust the neutrino flush time, since it was combined from `neutrino` and `neutrino_u` to simply `neutrino`
Needs a rebase first
> Update neutrino ToO flush time

- rubin_scheduler/utils/consdb.py
This will be obsoleted by SP-2442 and whatever follows it, but is a quick fix in the mean time.
There will be a corresponding pull request on schedview_notebooks shortly.
> ticktes/SP-2539: Fix loading of tokens from files for consdb query

- rubin_scheduler/scheduler/detailers/dither_detailer.py
- rubin_scheduler/scheduler/features/conditions.py
- rubin_scheduler/scheduler/model_observatory/model_observatory.py
- rubin_scheduler/scheduler/schedulers/core_scheduler.py
- rubin_scheduler/utils/constants.py
- tests/scheduler/test_detailers.py
- tests/scheduler/test_utils.py
Have the `Conditions` object compute the `night` value rather than have it manually set. The `CoreScheduler` will override `conditions.survey_start_mjd` value with it's own.
> Make night be calculated rather than set by user

- rubin_scheduler/utils/camera_footprint.py
- tests/utils/test_camerafootprint.py
Have the camera footprint mask off anything beyond a given radius. Default of 1.94 degrees is a pretty minor change compared to just the full focal plane
> add max to camera footprint
